name: 'BinTray Upload'
description: 'Upload files to BinTray'
inputs:
  username:
    description: 'Login username'
    required: true
  apikey:
    description: 'BinTray API key'
    required: true
  subject:
    description: 'Owner of the repository'
    required: false
  repository:
    description: 'Repository name'
    required: true
  package:
    description: 'Package name'
    required: true
  createPkg:
    description: "If set, will try to create package if it's missing"
    required: false
  version:
    description: 'Version name'
    required: true
  versionDescription:
    description: 'Version name'
    required: false
  versionVcsTag:
    description: 'Version name'
    required: false
  licenses:
    description: 'Package licences, comma-separated. For OSS, must of the licenses enumerated in https://bintray.com/api/v1/licenses/oss_licenses'
    required: true
  filesGlob:
    description: 'File glob to upload'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
